
name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /tmp/arrgbot
            cd /tmp/arrgbot
            git clone https://github.com/${GITHUB_REPOSITORY}.git


# docker-compose --env-file /arrgbot_env -p arrgbot up --build -d
# - docker-compose --env-file /arrgbot_env -p arrgbot up --build -d


